[package]
name = "unified"
version.workspace = true
edition.workspace = true

[dependencies]
serde.workspace = true
toml.workspace = true
async-trait.workspace = true
futures.workspace = true
libp2p.workspace = true
clap.workspace = true
log.workspace = true
env_logger.workspace = true
uuid.workspace = true
reqwest.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
bincode.workspace = true
anyhow.workspace = true
xxhash-rust.workspace = true
serde_json.workspace = true
rand.workspace = true
mongodb.workspace = true
redis.workspace = true
tokio.workspace = true
tokio-stream.workspace = true

pipeline = { path = "../pipeline" }
peyk.workspace = true
anbar.workspace = true

